In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
train_dtype = {
    'Store':'int16',
    'DayOfWeek':'int16',
    'Date':'str',
    'Sales':'float',
    'Customers':'float',
    'Open':'int16',
    'Promo':'int16',
    'StateHoliday':'str',
    'SchoolHoliday':'int16'
}
test_dtype = {
    'Id':'int32',
    'Store':'int16',
    'DayOfWeek':'int16',
    'Date':'str',
    'Promo':'int16',
    'StateHoliday':'str',
    'SchoolHoliday':'int16'
}
parse_dates = ['Date']
store_col = ['Store', 'StoreType', 'Assortment']

In [3]:
store = pd.read_csv('../data/rossman_data/store.csv',usecols=store_col)
train = pd.read_csv('../data/rossman_data/train.csv',dtype=train_dtype,parse_dates=parse_dates)
test = pd.read_csv('../data/rossman_data/test.csv',dtype=test_dtype,parse_dates=parse_dates)
test.Open =test.copy().Open.fillna(0.0).astype('int16')
test['Sales']=np.zeros(test.shape[0])

In [4]:
train_store_set = set(train.Store)
test_store_set = set(test.Store)
store_list = []
for s in train_store_set:
    if s in test_store_set:
        store_list.append(s)
train = train[train.Store.isin(store_list)]

In [5]:
train.shape

(773231, 9)

In [6]:
train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263.0,555.0,1,1,0,1
2,3,5,2015-07-31,8314.0,821.0,1,1,0,1
6,7,5,2015-07-31,15344.0,1414.0,1,1,0,1
7,8,5,2015-07-31,8492.0,833.0,1,1,0,1
8,9,5,2015-07-31,8565.0,687.0,1,1,0,1

In [7]:
test.head()

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday,Sales
0,1,1,4,2015-09-17,1,1,0,0,0.0
1,2,3,4,2015-09-17,1,1,0,0,0.0
2,3,7,4,2015-09-17,1,1,0,0,0.0
3,4,8,4,2015-09-17,1,1,0,0,0.0
4,5,9,4,2015-09-17,1,1,0,0,0.0

In [8]:
store.head()

   Store StoreType Assortment
0      1         c          a
1      2         a          a
2      3         a          a
3      4         c          c
4      5         a          a

In [9]:
train['dom'] = train.Date.dt.day
test['dom'] = test.Date.dt.day
train['doy'] = train.Date.dt.dayofyear
test['doy'] = test.Date.dt.dayofyear
train['quarter'] = train.Date.dt.quarter
test['quarter'] = test.Date.dt.quarter
train['month'] = train.Date.dt.month
test['month'] = test.Date.dt.month
train['week'] = train.Date.dt.week
test['week'] = test.Date.dt.week

In [10]:
train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,dom,doy,quarter,month,week
0,1,5,2015-07-31,5263.0,555.0,1,1,0,1,31,212,3,7,31
2,3,5,2015-07-31,8314.0,821.0,1,1,0,1,31,212,3,7,31
6,7,5,2015-07-31,15344.0,1414.0,1,1,0,1,31,212,3,7,31
7,8,5,2015-07-31,8492.0,833.0,1,1,0,1,31,212,3,7,31
8,9,5,2015-07-31,8565.0,687.0,1,1,0,1,31,212,3,7,31

In [11]:
train.Date.max(),train.Date.min()

(Timestamp('2015-07-31 00:00:00'), Timestamp('2013-01-01 00:00:00'))

In [12]:
# to get the train and validation marker as Id column, which is good to concat with test set
special_date = train.Date.iloc[49060]
ID = np.zeros(train.shape[0])
ID[train.Date>special_date] = np.ones(len(ID[train.Date>special_date]))*-50000 # validation set
ID[train.Date<=special_date] = np.ones(len(ID[train.Date<=special_date]))*50000 # train set
train['Id'] = ID.astype('int32')

In [13]:
train.shape,test.shape

((773231, 15), (41088, 14))

In [14]:
full_data = pd.concat([train.drop('Customers',axis=1)[::-1],test[::-1]],axis=0)

In [15]:
full_data.head()

,Date,DayOfWeek,Id,Open,Promo,Sales,SchoolHoliday,StateHoliday,Store,dom,doy,month,quarter,week
1017208,2013-01-01,2,50000,0,0,0.0,1,a,1115,1,1,1,1,1
1017207,2013-01-01,2,50000,0,0,0.0,1,a,1114,1,1,1,1,1
1017206,2013-01-01,2,50000,0,0,0.0,1,a,1113,1,1,1,1,1
1017205,2013-01-01,2,50000,0,0,0.0,1,a,1112,1,1,1,1,1
1017204,2013-01-01,2,50000,0,0,0.0,1,a,1111,1,1,1,1,1

In [16]:
full_data = full_data.merge(store,how='left',on='Store')

In [17]:
full_data.head()

,Date,DayOfWeek,Id,Open,Promo,Sales,SchoolHoliday,StateHoliday,Store,dom,doy,month,quarter,week,StoreType,Assortment
0,2013-01-01,2,50000,0,0,0.0,1,a,1115,1,1,1,1,1,d,c
1,2013-01-01,2,50000,0,0,0.0,1,a,1114,1,1,1,1,1,a,c
2,2013-01-01,2,50000,0,0,0.0,1,a,1113,1,1,1,1,1,a,c
3,2013-01-01,2,50000,0,0,0.0,1,a,1112,1,1,1,1,1,c,c
4,2013-01-01,2,50000,0,0,0.0,1,a,1111,1,1,1,1,1,a,a

In [18]:
lbl = LabelEncoder()
for col in ['DayOfWeek','SchoolHoliday','StateHoliday','Store','dom','doy',
           'month','quarter','week','StoreType','Assortment']:
    full_data[col] = lbl.fit_transform(full_data[col])

In [19]:
full_data.reset_index(drop=True,inplace=True)

In [20]:
full_data.head()

,Date,DayOfWeek,Id,Open,Promo,Sales,SchoolHoliday,StateHoliday,Store,dom,doy,month,quarter,week,StoreType,Assortment
0,2013-01-01,1,50000,0,0,0.0,1,1,855,0,0,0,0,0,3,2
1,2013-01-01,1,50000,0,0,0.0,1,1,854,0,0,0,0,0,0,2
2,2013-01-01,1,50000,0,0,0.0,1,1,853,0,0,0,0,0,0,2
3,2013-01-01,1,50000,0,0,0.0,1,1,852,0,0,0,0,0,2,2
4,2013-01-01,1,50000,0,0,0.0,1,1,851,0,0,0,0,0,0,0

In [32]:
full_data['Store_'] = full_data['Store'].copy()

In [33]:
feature_list = ['DayOfWeek','Id','Open','Promo',
               'Sales','SchoolHoliday','StateHoliday','Store','dom',
               'doy','month','quarter','week','StoreType','Assortment']

In [34]:
feature_dict = {i:None for i in feature_list}

In [38]:
for k in feature_dict.keys():
    feature_dict[k]=full_data[['Store_','Date',k]].set_index(['Store_','Date']).unstack(-1,fill_value=0)
    print(k,feature_dict[k].shape)

DayOfWeek (856, 990)
Id (856, 990)
Open (856, 990)
Promo (856, 990)
Sales (856, 990)
SchoolHoliday (856, 990)
StateHoliday (856, 990)
Store (856, 990)
dom (856, 990)
doy (856, 990)
month (856, 990)
quarter (856, 990)
week (856, 990)
StoreType (856, 990)
Assortment (856, 990)

In [43]:
feature_dict['Sales'].iloc[:,-160:]

            Sales                                                         \
Date   2015-04-11 2015-04-12 2015-04-13 2015-04-14 2015-04-15 2015-04-16
Store_
0          4173.0        0.0     5377.0     4648.0     4110.0     4116.0
1          4008.0        0.0     9563.0     9274.0     8651.0     8336.0
2          5479.0        0.0    11693.0    11185.0     9020.0     8168.0
3          3546.0        0.0     9881.0     8357.0     6489.0     8516.0
4          6837.0        0.0    11968.0     8416.0     7444.0     7644.0
5          4586.0        0.0     8442.0     7002.0     5948.0     5915.0
6          5550.0        0.0     9625.0     8499.0     8632.0     7523.0
7          6235.0        0.0    11377.0     9775.0     8764.0     8602.0
8          4411.0        0.0     7761.0     6119.0     5239.0     6301.0
9          4214.0        0.0     7946.0     6872.0     5422.0     6360.0
10         5315.0        0.0     9486.0     8304.0     6142.0     7123.0
11         5121.0        0.0    10511.0     9429.0     8955.0     8743.0
12         4719.0        0.0     9801.0     7616.0     6673.0     7730.0
13         6030.0        0.0    10726.0    10032.0     9505.0    10360.0
14         5236.0        0.0     7859.0     6007.0     6633.0     5672.0
15         3355.0        0.0     6206.0     6109.0     5481.0     4815.0
16         4925.0        0.0     8739.0     5793.0     6140.0     6315.0
17         7657.0        0.0    15163.0    10892.0    10084.0    10016.0
18         8721.0        0.0    14376.0    12359.0     9793.0    11610.0
19         7149.0        0.0    15122.0    12703.0    10834.0    11264.0
20         7669.0        0.0    13269.0     9309.0     7847.0     9215.0
21         3965.0        0.0     5325.0     4830.0     3728.0     4684.0
22         5524.0        0.0     6979.0     6382.0     5746.0     5192.0
23         2287.0        0.0     6549.0     5292.0     4537.0     4846.0
24         8304.0        0.0    11473.0     8791.0     7665.0     8076.0
25         8480.0        0.0    16891.0    12920.0    12256.0    13925.0
26         9072.0        0.0    10785.0    10712.0     9897.0     9527.0
27         6778.0        0.0     9936.0     6732.0     6029.0     6391.0
28         3231.0        0.0    10487.0     7051.0     6474.0     8158.0
29         4982.0        0.0     5203.0     5314.0     4628.0     4750.0
...           ...        ...        ...        ...        ...        ...
826        3119.0        0.0     7862.0     5606.0     5048.0     5013.0
827        6045.0        0.0    10573.0     8569.0     8055.0     8528.0
828        6218.0        0.0    13236.0    11293.0     8432.0     9150.0
829       11737.0        0.0    14023.0    11259.0    10438.0    10989.0
830        5749.0        0.0     7682.0     6023.0     5344.0     5352.0
831        5130.0        0.0     7103.0     6815.0     5624.0     6734.0
832        4163.0        0.0    10204.0     7937.0     6347.0     6628.0
833        6096.0        0.0     8807.0     7225.0     7151.0     7048.0
834        3199.0        0.0     8001.0     7534.0     6016.0     6342.0
835       10187.0        0.0    14407.0    11397.0    10102.0    10674.0
836        6457.0        0.0    13429.0     9408.0     7906.0     8034.0
837       14416.0        0.0    15157.0    13347.0    11921.0    11669.0
838        5792.0        0.0     5344.0     5752.0     4813.0     4769.0
839        4712.0        0.0     8933.0     6481.0     5872.0     6072.0
840        7523.0    12528.0    11531.0    10690.0    10310.0     9872.0
841        5974.0     3999.0    10569.0     8319.0     7522.0     7650.0
842        3034.0        0.0     8385.0     6707.0     5969.0     6239.0
843        7861.0        0.0    15848.0    12343.0    10444.0    11063.0
844        5997.0        0.0     8675.0     7707.0     6824.0     6817.0
845        5698.0        0.0     8426.0     6448.0     5726.0     5140.0
846        5805.0        0.0     7388.0     6199.0     4874.0     5909.0
847        5129.0        0.0     8625.0     5878.0     5134.0     5242.0
848        2882.0        0.0     7180.0     5550.0     4931.0     6099.0
849        5499.0        0.0     9667.0     8920.0     7847.0     6267.0
850        3363.0        0.0     7488.0     6102.0     5093.0     4913.0
851        3367.0        0.0     8528.0     5787.0     5535.0     5347.0
852        7500.0        0.0    15465.0    10302.0     9484.0    10810.0
853        5070.0        0.0     7854.0     7075.0     6348.0     7460.0
854       23411.0        0.0    25765.0    23495.0    22887.0    21498.0
855        7361.0        0.0     9579.0     7790.0     6440.0     6964.0

                                                      ...                 \
Date   2015-04-17 2015-04-18 2015-04-19 2015-04-20    ...     2015-09-08
Store_                                                ...
0          4718.0     4594.0        0.0     3722.0    ...            0.0
1          7735.0     3772.0        0.0     5238.0    ...            0.0
2          9300.0     5534.0        0.0     7587.0    ...            0.0
3          6049.0     3834.0        0.0     5591.0    ...            0.0
4          8346.0     6685.0        0.0     6429.0    ...            0.0
5          6521.0     5807.0        0.0     5130.0    ...            0.0
6          7262.0     5331.0        0.0     6556.0    ...            0.0
7          8576.0     6901.0        0.0     6416.0    ...            0.0
8          5889.0     4748.0        0.0     3534.0    ...            0.0
9          6947.0     3421.0        0.0     5158.0    ...            0.0
10         7646.0     5209.0        0.0     5211.0    ...            0.0
11         9012.0     5654.0        0.0     7812.0    ...            0.0
12         7433.0     4456.0        0.0     5628.0    ...            0.0
13         6919.0     5634.0        0.0     9564.0    ...            0.0
14         7703.0     5325.0        0.0     3818.0    ...            0.0
15         5159.0     3486.0        0.0     3552.0    ...            0.0
16         7215.0     4546.0        0.0     4245.0    ...            0.0
17        11058.0     7919.0        0.0     7612.0    ...            0.0
18        10806.0     9045.0        0.0     9841.0    ...            0.0
19        11018.0     7758.0        0.0     7280.0    ...            0.0
20         8867.0     8007.0        0.0     5994.0    ...            0.0
21         3749.0     3362.0        0.0     2974.0    ...            0.0
22         5900.0     4593.0        0.0     3728.0    ...            0.0
23         4389.0     2770.0        0.0     4241.0    ...            0.0
24         7791.0     8661.0        0.0     7294.0    ...            0.0
25        12809.0     8649.0        0.0     8330.0    ...            0.0
26         8950.0     9248.0        0.0     9026.0    ...            0.0
27         6728.0     5840.0        0.0     4636.0    ...            0.0
28         7751.0     4894.0        0.0     6436.0    ...            0.0
29         5063.0     4940.0        0.0     3442.0    ...            0.0
...           ...        ...        ...        ...    ...            ...
826        5303.0     2502.0        0.0     3586.0    ...            0.0
827        8966.0     5560.0        0.0     5397.0    ...            0.0
828        9553.0     5661.0        0.0     6083.0    ...            0.0
829        9938.0    11792.0        0.0    10953.0    ...            0.0
830        6254.0     6296.0        0.0     4367.0    ...            0.0
831        6928.0     5784.0        0.0     6138.0    ...            0.0
832        6886.0     3629.0        0.0     4546.0    ...            0.0
833        7538.0     6156.0        0.0     4408.0    ...            0.0
834        6755.0     3444.0        0.0     4079.0    ...            0.0
835       12235.0     9733.0        0.0     8785.0    ...            0.0
836        8914.0     5898.0        0.0     7415.0    ...            0.0
837       11550.0    15363.0        0.0    10972.0    ...            0.0
838        4516.0     6503.0        0.0     4171.0    ...            0.0
839        7407.0     4705.0        0.0     4701.0    ...            0.0
840       11166.0     7704.0    13194.0     9921.0    ...            0.0
841        7534.0     6539.0     3814.0     7193.0    ...            0.0
842        6055.0     2779.0        0.0     3732.0    ...            0.0
843       10419.0     7815.0        0.0     8501.0    ...            0.0
844        5889.0     6971.0        0.0     6666.0    ...            0.0
845        6413.0     5699.0        0.0     4505.0    ...            0.0
846        5795.0     5607.0        0.0     4388.0    ...            0.0
847        5176.0     4689.0        0.0     3932.0    ...            0.0
848        4973.0     3087.0        0.0     4903.0    ...            0.0
849        6587.0     5573.0        0.0     4863.0    ...            0.0
850        4628.0     3833.0        0.0     4717.0    ...            0.0
851        6054.0     2920.0        0.0     4607.0    ...            0.0
852       10081.0     7475.0        0.0     6687.0    ...            0.0
853        5639.0     6062.0        0.0     5423.0    ...            0.0
854       23806.0    22837.0        0.0    20041.0    ...            0.0
855        8309.0     7154.0        0.0     5127.0    ...            0.0

                                                                          \
Date   2015-09-09 2015-09-10 2015-09-11 2015-09-12 2015-09-13 2015-09-14
Store_
0             0.0        0.0        0.0        0.0        0.0        0.0
1             0.0        0.0        0.0        0.0        0.0        0.0
2             0.0        0.0        0.0        0.0        0.0        0.0
3             0.0        0.0        0.0        0.0        0.0        0.0
4             0.0        0.0        0.0        0.0        0.0        0.0
5             0.0        0.0        0.0        0.0        0.0        0.0
6             0.0        0.0        0.0        0.0        0.0        0.0
7             0.0        0.0        0.0        0.0        0.0        0.0
8             0.0        0.0        0.0        0.0        0.0        0.0
9             0.0        0.0        0.0        0.0        0.0        0.0
10            0.0        0.0        0.0        0.0        0.0        0.0
11            0.0        0.0        0.0        0.0        0.0        0.0
12            0.0        0.0        0.0        0.0        0.0        0.0
13            0.0        0.0        0.0        0.0        0.0        0.0
14            0.0        0.0        0.0        0.0        0.0        0.0
15            0.0        0.0        0.0        0.0        0.0        0.0
16            0.0        0.0        0.0        0.0        0.0        0.0
17            0.0        0.0        0.0        0.0        0.0        0.0
18            0.0        0.0        0.0        0.0        0.0        0.0
19            0.0        0.0        0.0        0.0        0.0        0.0
20            0.0        0.0        0.0        0.0        0.0        0.0
21            0.0        0.0        0.0        0.0        0.0        0.0
22            0.0        0.0        0.0        0.0        0.0        0.0
23            0.0        0.0        0.0        0.0        0.0        0.0
24            0.0        0.0        0.0        0.0        0.0        0.0
25            0.0        0.0        0.0        0.0        0.0        0.0
26            0.0        0.0        0.0        0.0        0.0        0.0
27            0.0        0.0        0.0        0.0        0.0        0.0
28            0.0        0.0        0.0        0.0        0.0        0.0
29            0.0        0.0        0.0        0.0        0.0        0.0
...           ...        ...        ...        ...        ...        ...
826           0.0        0.0        0.0        0.0        0.0        0.0
827           0.0        0.0        0.0        0.0        0.0        0.0
828           0.0        0.0        0.0        0.0        0.0        0.0
829           0.0        0.0        0.0        0.0        0.0        0.0
830           0.0        0.0        0.0        0.0        0.0        0.0
831           0.0        0.0        0.0        0.0        0.0        0.0
832           0.0        0.0        0.0        0.0        0.0        0.0
833           0.0        0.0        0.0        0.0        0.0        0.0
834           0.0        0.0        0.0        0.0        0.0        0.0
835           0.0        0.0        0.0        0.0        0.0        0.0
836           0.0        0.0        0.0        0.0        0.0        0.0
837           0.0        0.0        0.0        0.0        0.0        0.0
838           0.0        0.0        0.0        0.0        0.0        0.0
839           0.0        0.0        0.0        0.0        0.0        0.0
840           0.0        0.0        0.0        0.0        0.0        0.0
841           0.0        0.0        0.0        0.0        0.0        0.0
842           0.0        0.0        0.0        0.0        0.0        0.0
843           0.0        0.0        0.0        0.0        0.0        0.0
844           0.0        0.0        0.0        0.0        0.0        0.0
845           0.0        0.0        0.0        0.0        0.0        0.0
846           0.0        0.0        0.0        0.0        0.0        0.0
847           0.0        0.0        0.0        0.0        0.0        0.0
848           0.0        0.0        0.0        0.0        0.0        0.0
849           0.0        0.0        0.0        0.0        0.0        0.0
850           0.0        0.0        0.0        0.0        0.0        0.0
851           0.0        0.0        0.0        0.0        0.0        0.0
852           0.0        0.0        0.0        0.0        0.0        0.0
853           0.0        0.0        0.0        0.0        0.0        0.0
854           0.0        0.0        0.0        0.0        0.0        0.0
855           0.0        0.0        0.0        0.0        0.0        0.0


Date   2015-09-15 2015-09-16 2015-09-17
Store_
0             0.0        0.0        0.0
1             0.0        0.0        0.0
2             0.0        0.0        0.0
3             0.0        0.0        0.0
4             0.0        0.0        0.0
5             0.0        0.0        0.0
6             0.0        0.0        0.0
7             0.0        0.0        0.0
8             0.0        0.0        0.0
9             0.0        0.0        0.0
10            0.0        0.0        0.0
11            0.0        0.0        0.0
12            0.0        0.0        0.0
13            0.0        0.0        0.0
14            0.0        0.0        0.0
15            0.0        0.0        0.0
16            0.0        0.0        0.0
17            0.0        0.0        0.0
18            0.0        0.0        0.0
19            0.0        0.0        0.0
20            0.0        0.0        0.0
21            0.0        0.0        0.0
22            0.0        0.0        0.0
23            0.0        0.0        0.0
24            0.0        0.0        0.0
25            0.0        0.0        0.0
26            0.0        0.0        0.0
27            0.0        0.0        0.0
28            0.0        0.0        0.0
29            0.0        0.0        0.0
...           ...        ...        ...
826           0.0        0.0        0.0
827           0.0        0.0        0.0
828           0.0        0.0        0.0
829           0.0        0.0        0.0
830           0.0        0.0        0.0
831           0.0        0.0        0.0
832           0.0        0.0        0.0
833           0.0        0.0        0.0
834           0.0        0.0        0.0
835           0.0        0.0        0.0
836           0.0        0.0        0.0
837           0.0        0.0        0.0
838           0.0        0.0        0.0
839           0.0        0.0        0.0
840           0.0        0.0        0.0
841           0.0        0.0        0.0
842           0.0        0.0        0.0
843           0.0        0.0        0.0
844           0.0        0.0        0.0
845           0.0        0.0        0.0
846           0.0        0.0        0.0
847           0.0        0.0        0.0
848           0.0        0.0        0.0
849           0.0        0.0        0.0
850           0.0        0.0        0.0
851           0.0        0.0        0.0
852           0.0        0.0        0.0
853           0.0        0.0        0.0
854           0.0        0.0        0.0
855           0.0        0.0        0.0

[856 rows x 160 columns]

In [44]:
train_dict = {i:None for i in feature_dict.keys()}
val_dict = {i:None for i in feature_dict.keys()}
test_dict = {i:None for i in feature_dict.keys()}

In [70]:
for k in test_dict.keys():
    test_dict[k] = feature_dict[k].iloc[:,-160:]
    val_dict[k] = feature_dict[k].iloc[:,-208:-48]

In [71]:
val_dict['Sales'].shape

(856, 160)

In [217]:
test[test.Store==115].shape

(48, 14)

In [218]:
def get_lookback(data,n=65,f=5):
    length = len(data)
    result = []
    for i in range(n,length,f):
        result.append(data[i-n:i])
    return np.expand_dims(np.array(result),2)

In [220]:
full_data.Id.min()

-50000

In [191]:
len(set(train.Store)),len(set(test.Store))

(856, 856)

In [226]:
get_lookback(train.Sales[train.Store==1],n=160,f=48).shape

(17, 160, 1)

In [221]:
full_data.columns

Index(['Date', 'DayOfWeek', 'Id', 'Open', 'Promo', 'Sales', 'SchoolHoliday',
       'StateHoliday', 'Store', 'dom', 'doy', 'month', 'quarter', 'week',
       'StoreType', 'Assortment'],
      dtype='object')

In [285]:
attr_list = ['Id','Sales','DayOfWeek',  'Open', 'Promo',  'SchoolHoliday',
       'StateHoliday', 'Store', 'dom', 'doy', 'month', 'quarter', 'week',
       'StoreType', 'Assortment']
store_list = full_data.Store.unique()

In [289]:
store_list.shape

(856,)

In [231]:
np.concatenate?

In [292]:
def print_data(data):
    '''
    def get_one_store(col,s):
        return get_lookback(data[col][data.Store==s],160,48)
    
    result = get_one_store(attr_list[0],store_list[0])
    print(result.shape)
    print(get_one_store(attr_list[0],store_list[1]).shape)
    '''
    result = get_lookback(data[attr_list[0]][data.Store==store_list[0]],n=160,f=48)
    for s in store_list[1:]:
        print(get_lookback(data[attr_list[0]][data.Store==s],n=160,f=48).shape)
        result = np.concatenate((result,get_lookback(data[attr_list[0]][data.Store==s],n=160,f=48)),axis=0)
    for col in attr_list[1:]:
        store_tmp = get_lookback(data[col][data.Store==store_list[0]],n=160,f=48)
        for s in store_list[1:]:
            tmp = get_lookback(data[col][data.Store==s],n=160,f=48)
            #print(tmp.shape,store_tmp.shape)
            store_tmp = np.concatenate((store_tmp,tmp),axis=0)
        result = np.concatenate((result,store_tmp),axis=2)
    
    return result

In [296]:
data = print_data(full_data)

(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)

(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(14, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)
(18, 160, 1)

In [300]:
np.transpose(data,[2,0,1]).shape

(15, 14688, 160)

In [298]:
data[:,:,[data[:,:,0]==50000]].shape

IndexError: too many indices for array

In [294]:
result = get_lookback(full_data.StoreType[full_data.Store==store_list[0]],n=160,f=48)
result2 = get_lookback(full_data.StoreType[full_data.Store==store_list[1]],n=160,f=48)

In [295]:
for s in store_list[1:]:
    print(result.shape,s)
    result = np.concatenate((result,get_lookback(full_data.StoreType[full_data.Store==s],n=160,f=48)),axis=0)

(18, 160, 1) 854
(36, 160, 1) 853
(54, 160, 1) 852
(72, 160, 1) 851
(90, 160, 1) 850
(104, 160, 1) 849
(118, 160, 1) 848
(136, 160, 1) 847
(154, 160, 1) 846
(168, 160, 1) 845
(186, 160, 1) 844
(200, 160, 1) 843
(218, 160, 1) 842
(236, 160, 1) 841
(254, 160, 1) 840
(272, 160, 1) 839
(290, 160, 1) 838
(304, 160, 1) 837
(318, 160, 1) 836
(336, 160, 1) 835
(354, 160, 1) 834
(372, 160, 1) 833
(390, 160, 1) 832
(408, 160, 1) 831
(426, 160, 1) 830
(444, 160, 1) 829
(458, 160, 1) 828
(476, 160, 1) 827
(494, 160, 1) 826
(512, 160, 1) 825
(530, 160, 1) 824
(548, 160, 1) 823
(566, 160, 1) 822
(584, 160, 1) 821
(602, 160, 1) 820
(620, 160, 1) 819
(634, 160, 1) 818
(652, 160, 1) 817
(666, 160, 1) 816
(684, 160, 1) 815
(702, 160, 1) 814
(720, 160, 1) 813
(738, 160, 1) 812
(756, 160, 1) 811
(774, 160, 1) 810
(792, 160, 1) 809
(810, 160, 1) 808
(824, 160, 1) 807
(842, 160, 1) 806
(860, 160, 1) 805
(878, 160, 1) 804
(896, 160, 1) 803
(914, 160, 1) 802
(928, 160, 1) 801
(946, 160, 1) 800
(964, 160, 1) 799
(982, 160, 1) 798
(1000, 160, 1) 797
(1018, 160, 1) 796
(1032, 160, 1) 795
(1050, 160, 1) 794
(1068, 160, 1) 793
(1082, 160, 1) 792
(1100, 160, 1) 791
(1118, 160, 1) 790
(1136, 160, 1) 789
(1154, 160, 1) 788
(1168, 160, 1) 787
(1186, 160, 1) 786
(1204, 160, 1) 785
(1222, 160, 1) 784
(1240, 160, 1) 783
(1258, 160, 1) 782
(1272, 160, 1) 781
(1290, 160, 1) 780
(1308, 160, 1) 779
(1326, 160, 1) 778
(1344, 160, 1) 777
(1358, 160, 1) 776
(1376, 160, 1) 775
(1394, 160, 1) 774
(1408, 160, 1) 773
(1426, 160, 1) 772
(1444, 160, 1) 771
(1462, 160, 1) 770
(1476, 160, 1) 769
(1494, 160, 1) 768
(1508, 160, 1) 767
(1526, 160, 1) 766
(1544, 160, 1) 765
(1562, 160, 1) 764
(1580, 160, 1) 763
(1598, 160, 1) 762
(1612, 160, 1) 760
(1630, 160, 1) 759
(1648, 160, 1) 758
(1666, 160, 1) 757
(1684, 160, 1) 756
(1702, 160, 1) 755
(1716, 160, 1) 754
(1734, 160, 1) 753
(1752, 160, 1) 752
(1766, 160, 1) 751
(1784, 160, 1) 750
(1802, 160, 1) 749
(1820, 160, 1) 748
(1838, 160, 1) 747
(1856, 160, 1) 746
(1874, 160, 1) 745
(1892, 160, 1) 744
(1910, 160, 1) 743
(1928, 160, 1) 742
(1946, 160, 1) 741
(1964, 160, 1) 740
(1982, 160, 1) 739
(2000, 160, 1) 738
(2014, 160, 1) 737
(2032, 160, 1) 736
(2050, 160, 1) 735
(2068, 160, 1) 734
(2086, 160, 1) 733
(2104, 160, 1) 732
(2122, 160, 1) 731
(2140, 160, 1) 730
(2158, 160, 1) 729
(2176, 160, 1) 728
(2190, 160, 1) 727
(2208, 160, 1) 726
(2226, 160, 1) 725
(2244, 160, 1) 724
(2262, 160, 1) 723
(2280, 160, 1) 722
(2298, 160, 1) 721
(2312, 160, 1) 720
(2330, 160, 1) 719
(2348, 160, 1) 718
(2366, 160, 1) 717
(2384, 160, 1) 716
(2402, 160, 1) 715
(2420, 160, 1) 714
(2438, 160, 1) 713
(2456, 160, 1) 712
(2474, 160, 1) 711
(2488, 160, 1) 710
(2502, 160, 1) 709
(2520, 160, 1) 708
(2538, 160, 1) 707
(2552, 160, 1) 706
(2570, 160, 1) 705
(2588, 160, 1) 704
(2606, 160, 1) 703
(2624, 160, 1) 702
(2638, 160, 1) 701
(2656, 160, 1) 700
(2674, 160, 1) 699
(2692, 160, 1) 698
(2710, 160, 1) 697
(2724, 160, 1) 696
(2738, 160, 1) 695
(2752, 160, 1) 694
(2770, 160, 1) 693
(2784, 160, 1) 692
(2802, 160, 1) 691
(2820, 160, 1) 690
(2838, 160, 1) 689
(2856, 160, 1) 688
(2870, 160, 1) 687
(2888, 160, 1) 686
(2902, 160, 1) 685
(2920, 160, 1) 684
(2938, 160, 1) 683
(2956, 160, 1) 682
(2974, 160, 1) 681
(2988, 160, 1) 680
(3006, 160, 1) 679
(3024, 160, 1) 678
(3042, 160, 1) 677
(3060, 160, 1) 676
(3074, 160, 1) 675
(3092, 160, 1) 674
(3110, 160, 1) 673
(3128, 160, 1) 672
(3146, 160, 1) 671
(3164, 160, 1) 670
(3182, 160, 1) 669
(3200, 160, 1) 668
(3218, 160, 1) 667
(3236, 160, 1) 666
(3254, 160, 1) 665
(3272, 160, 1) 664
(3290, 160, 1) 663
(3308, 160, 1) 662
(3326, 160, 1) 661
(3340, 160, 1) 660
(3354, 160, 1) 659
(3372, 160, 1) 658
(3390, 160, 1) 657
(3408, 160, 1) 656
(3426, 160, 1) 655
(3444, 160, 1) 654
(3458, 160, 1) 653
(3476, 160, 1) 652
(3494, 160, 1) 651
(3512, 160, 1) 650
(3530, 160, 1) 649
(3548, 160, 1) 648
(3566, 160, 1) 647
(3584, 160, 1) 646
(3598, 160, 1) 645
(3616, 160, 1) 644
(3634, 160, 1) 643
(3652, 160, 1) 642
(3670, 160, 1) 641
(3688, 160, 1) 640
(3706, 160, 1) 639
(3724, 160, 1) 638
(3742, 160, 1) 637
(3756, 160, 1) 636
(3774, 160, 1) 635
(3792, 160, 1) 634
(3810, 160, 1) 633
(3824, 160, 1) 632
(3842, 160, 1) 631
(3860, 160, 1) 630
(3878, 160, 1) 629
(3892, 160, 1) 628
(3910, 160, 1) 627
(3928, 160, 1) 626
(3946, 160, 1) 625
(3964, 160, 1) 624
(3982, 160, 1) 623
(3996, 160, 1) 622
(4010, 160, 1) 621
(4024, 160, 1) 620
(4042, 160, 1) 619
(4060, 160, 1) 618
(4078, 160, 1) 617
(4096, 160, 1) 616
(4114, 160, 1) 615
(4128, 160, 1) 614
(4146, 160, 1) 613
(4164, 160, 1) 612
(4182, 160, 1) 611
(4200, 160, 1) 610
(4218, 160, 1) 609
(4236, 160, 1) 608
(4254, 160, 1) 607
(4272, 160, 1) 606
(4290, 160, 1) 605
(4308, 160, 1) 604
(4322, 160, 1) 603
(4340, 160, 1) 602
(4358, 160, 1) 601
(4372, 160, 1) 600
(4390, 160, 1) 599
(4408, 160, 1) 598
(4426, 160, 1) 597
(4440, 160, 1) 596
(4458, 160, 1) 595
(4476, 160, 1) 594
(4494, 160, 1) 593
(4512, 160, 1) 592
(4526, 160, 1) 591
(4544, 160, 1) 590
(4562, 160, 1) 589
(4580, 160, 1) 588
(4598, 160, 1) 587
(4616, 160, 1) 586
(4634, 160, 1) 585
(4652, 160, 1) 584
(4670, 160, 1) 583
(4688, 160, 1) 582
(4706, 160, 1) 581
(4724, 160, 1) 580
(4738, 160, 1) 579
(4756, 160, 1) 578
(4774, 160, 1) 577
(4792, 160, 1) 576
(4806, 160, 1) 575
(4824, 160, 1) 574
(4842, 160, 1) 573
(4860, 160, 1) 572
(4874, 160, 1) 571
(4892, 160, 1) 570
(4910, 160, 1) 569
(4924, 160, 1) 568
(4942, 160, 1) 567
(4960, 160, 1) 566
(4978, 160, 1) 565
(4996, 160, 1) 564
(5014, 160, 1) 563
(5032, 160, 1) 562
(5050, 160, 1) 561
(5068, 160, 1) 560
(5086, 160, 1) 559
(5104, 160, 1) 558
(5122, 160, 1) 557
(5140, 160, 1) 556
(5158, 160, 1) 555
(5172, 160, 1) 554
(5190, 160, 1) 553
(5208, 160, 1) 552
(5222, 160, 1) 551
(5240, 160, 1) 550
(5258, 160, 1) 549
(5272, 160, 1) 548
(5286, 160, 1) 547
(5300, 160, 1) 546
(5318, 160, 1) 545
(5332, 160, 1) 544
(5350, 160, 1) 543
(5368, 160, 1) 542
(5382, 160, 1) 541
(5396, 160, 1) 540
(5414, 160, 1) 539
(5432, 160, 1) 538
(5450, 160, 1) 537
(5468, 160, 1) 536
(5486, 160, 1) 535
(5500, 160, 1) 534
(5518, 160, 1) 533
(5536, 160, 1) 532
(5554, 160, 1) 531
(5572, 160, 1) 530
(5590, 160, 1) 529
(5608, 160, 1) 528
(5626, 160, 1) 527
(5640, 160, 1) 526
(5658, 160, 1) 525
(5676, 160, 1) 524
(5694, 160, 1) 523
(5708, 160, 1) 522
(5726, 160, 1) 521
(5744, 160, 1) 520
(5762, 160, 1) 519
(5780, 160, 1) 518
(5794, 160, 1) 517
(5808, 160, 1) 516
(5822, 160, 1) 515
(5840, 160, 1) 514
(5858, 160, 1) 513
(5876, 160, 1) 512
(5894, 160, 1) 511
(5912, 160, 1) 510
(5930, 160, 1) 509
(5944, 160, 1) 508
(5962, 160, 1) 507
(5980, 160, 1) 506
(5998, 160, 1) 505
(6016, 160, 1) 504
(6034, 160, 1) 503
(6052, 160, 1) 502
(6070, 160, 1) 501
(6084, 160, 1) 500
(6102, 160, 1) 499
(6116, 160, 1) 498
(6134, 160, 1) 497
(6148, 160, 1) 496
(6166, 160, 1) 495
(6184, 160, 1) 494
(6202, 160, 1) 493
(6220, 160, 1) 492
(6238, 160, 1) 491
(6252, 160, 1) 490
(6266, 160, 1) 489
(6280, 160, 1) 488
(6294, 160, 1) 487
(6312, 160, 1) 486
(6330, 160, 1) 485
(6344, 160, 1) 484
(6362, 160, 1) 483
(6380, 160, 1) 482
(6398, 160, 1) 481
(6416, 160, 1) 480
(6434, 160, 1) 479
(6452, 160, 1) 478
(6470, 160, 1) 477
(6484, 160, 1) 476
(6498, 160, 1) 475
(6516, 160, 1) 474
(6534, 160, 1) 473
(6552, 160, 1) 472
(6566, 160, 1) 471
(6580, 160, 1) 470
(6598, 160, 1) 469
(6616, 160, 1) 468
(6630, 160, 1) 467
(6648, 160, 1) 466
(6666, 160, 1) 465
(6684, 160, 1) 464
(6702, 160, 1) 463
(6716, 160, 1) 462
(6734, 160, 1) 461
(6752, 160, 1) 460
(6770, 160, 1) 459
(6788, 160, 1) 458
(6806, 160, 1) 457
(6824, 160, 1) 456
(6842, 160, 1) 455
(6856, 160, 1) 454
(6874, 160, 1) 453
(6892, 160, 1) 452
(6910, 160, 1) 451
(6928, 160, 1) 450
(6946, 160, 1) 449
(6964, 160, 1) 448
(6982, 160, 1) 447
(7000, 160, 1) 446
(7018, 160, 1) 445
(7032, 160, 1) 444
(7050, 160, 1) 443
(7064, 160, 1) 442
(7082, 160, 1) 441
(7096, 160, 1) 440
(7114, 160, 1) 439
(7132, 160, 1) 438
(7150, 160, 1) 437
(7168, 160, 1) 436
(7186, 160, 1) 435
(7204, 160, 1) 434
(7222, 160, 1) 433
(7240, 160, 1) 432
(7258, 160, 1) 431
(7276, 160, 1) 430
(7294, 160, 1) 429
(7308, 160, 1) 428
(7326, 160, 1) 427
(7344, 160, 1) 426
(7362, 160, 1) 425
(7380, 160, 1) 424
(7398, 160, 1) 423
(7416, 160, 1) 422
(7434, 160, 1) 421
(7448, 160, 1) 420
(7466, 160, 1) 419
(7484, 160, 1) 418
(7498, 160, 1) 417
(7516, 160, 1) 416
(7530, 160, 1) 415
(7544, 160, 1) 414
(7562, 160, 1) 413
(7580, 160, 1) 412
(7598, 160, 1) 411
(7616, 160, 1) 410
(7630, 160, 1) 409
(7648, 160, 1) 408
(7666, 160, 1) 407
(7684, 160, 1) 406
(7702, 160, 1) 405
(7720, 160, 1) 404
(7738, 160, 1) 403
(7756, 160, 1) 402
(7774, 160, 1) 401
(7788, 160, 1) 400
(7806, 160, 1) 399
(7824, 160, 1) 398
(7842, 160, 1) 397
(7856, 160, 1) 396
(7874, 160, 1) 395
(7892, 160, 1) 394
(7910, 160, 1) 393

(7924, 160, 1) 392
(7938, 160, 1) 391
(7956, 160, 1) 390
(7974, 160, 1) 389
(7992, 160, 1) 388
(8010, 160, 1) 387
(8028, 160, 1) 386
(8046, 160, 1) 385
(8064, 160, 1) 384
(8082, 160, 1) 383
(8100, 160, 1) 382
(8114, 160, 1) 381
(8128, 160, 1) 380
(8146, 160, 1) 379
(8160, 160, 1) 378
(8178, 160, 1) 377
(8196, 160, 1) 376
(8214, 160, 1) 375
(8228, 160, 1) 374
(8246, 160, 1) 373
(8260, 160, 1) 372
(8278, 160, 1) 371
(8296, 160, 1) 370
(8314, 160, 1) 369
(8328, 160, 1) 368
(8346, 160, 1) 367
(8364, 160, 1) 366
(8378, 160, 1) 365
(8396, 160, 1) 364
(8414, 160, 1) 363
(8432, 160, 1) 362
(8446, 160, 1) 361
(8464, 160, 1) 360
(8482, 160, 1) 359
(8500, 160, 1) 358
(8518, 160, 1) 357
(8536, 160, 1) 356
(8554, 160, 1) 355
(8572, 160, 1) 354
(8590, 160, 1) 353
(8608, 160, 1) 352
(8622, 160, 1) 351
(8640, 160, 1) 350
(8658, 160, 1) 349
(8676, 160, 1) 348
(8694, 160, 1) 347
(8712, 160, 1) 346
(8730, 160, 1) 345
(8748, 160, 1) 344
(8766, 160, 1) 343
(8784, 160, 1) 342
(8802, 160, 1) 341
(8820, 160, 1) 340
(8838, 160, 1) 339
(8856, 160, 1) 338
(8874, 160, 1) 337
(8892, 160, 1) 336
(8906, 160, 1) 335
(8924, 160, 1) 334
(8942, 160, 1) 333
(8960, 160, 1) 332
(8974, 160, 1) 331
(8988, 160, 1) 330
(9002, 160, 1) 329
(9016, 160, 1) 328
(9034, 160, 1) 327
(9052, 160, 1) 326
(9070, 160, 1) 325
(9088, 160, 1) 324
(9106, 160, 1) 323
(9120, 160, 1) 322
(9138, 160, 1) 321
(9156, 160, 1) 320
(9174, 160, 1) 319
(9192, 160, 1) 318
(9210, 160, 1) 317
(9224, 160, 1) 316
(9238, 160, 1) 315
(9256, 160, 1) 314
(9274, 160, 1) 313
(9292, 160, 1) 312
(9310, 160, 1) 311
(9324, 160, 1) 310
(9342, 160, 1) 309
(9360, 160, 1) 308
(9378, 160, 1) 307
(9396, 160, 1) 306
(9410, 160, 1) 305
(9428, 160, 1) 304
(9446, 160, 1) 303
(9464, 160, 1) 302
(9482, 160, 1) 301
(9500, 160, 1) 300
(9518, 160, 1) 299
(9536, 160, 1) 298
(9554, 160, 1) 297
(9572, 160, 1) 296
(9590, 160, 1) 295
(9608, 160, 1) 294
(9622, 160, 1) 293
(9640, 160, 1) 292
(9658, 160, 1) 291
(9676, 160, 1) 290
(9694, 160, 1) 289
(9712, 160, 1) 288
(9730, 160, 1) 287
(9748, 160, 1) 286
(9766, 160, 1) 285
(9784, 160, 1) 284
(9802, 160, 1) 283
(9820, 160, 1) 282
(9838, 160, 1) 281
(9852, 160, 1) 280
(9870, 160, 1) 279
(9888, 160, 1) 278
(9906, 160, 1) 277
(9924, 160, 1) 276
(9942, 160, 1) 275
(9960, 160, 1) 274
(9978, 160, 1) 273
(9996, 160, 1) 272
(10014, 160, 1) 271
(10032, 160, 1) 270
(10050, 160, 1) 269
(10064, 160, 1) 268
(10082, 160, 1) 267
(10100, 160, 1) 266
(10114, 160, 1) 265
(10132, 160, 1) 264
(10150, 160, 1) 263
(10164, 160, 1) 262
(10182, 160, 1) 261
(10200, 160, 1) 260
(10218, 160, 1) 259
(10236, 160, 1) 258
(10254, 160, 1) 257
(10272, 160, 1) 256
(10290, 160, 1) 255
(10308, 160, 1) 254
(10326, 160, 1) 253
(10344, 160, 1) 252
(10362, 160, 1) 251
(10380, 160, 1) 250
(10398, 160, 1) 249
(10416, 160, 1) 248
(10434, 160, 1) 247
(10452, 160, 1) 246
(10470, 160, 1) 245
(10488, 160, 1) 244
(10502, 160, 1) 243
(10520, 160, 1) 242
(10538, 160, 1) 241
(10556, 160, 1) 240
(10574, 160, 1) 239
(10592, 160, 1) 238
(10610, 160, 1) 237
(10628, 160, 1) 236
(10646, 160, 1) 235
(10660, 160, 1) 234
(10678, 160, 1) 233
(10696, 160, 1) 232
(10714, 160, 1) 231
(10732, 160, 1) 230
(10750, 160, 1) 229
(10768, 160, 1) 228
(10786, 160, 1) 227
(10800, 160, 1) 226
(10818, 160, 1) 225
(10836, 160, 1) 224
(10854, 160, 1) 223
(10872, 160, 1) 222
(10890, 160, 1) 221
(10908, 160, 1) 220
(10922, 160, 1) 219
(10936, 160, 1) 218
(10954, 160, 1) 217
(10968, 160, 1) 216
(10982, 160, 1) 215
(11000, 160, 1) 214
(11018, 160, 1) 213
(11032, 160, 1) 212
(11050, 160, 1) 211
(11064, 160, 1) 210
(11078, 160, 1) 209
(11096, 160, 1) 208
(11114, 160, 1) 207
(11132, 160, 1) 206
(11150, 160, 1) 205
(11168, 160, 1) 204
(11186, 160, 1) 203
(11204, 160, 1) 202
(11218, 160, 1) 201
(11236, 160, 1) 200
(11254, 160, 1) 199
(11268, 160, 1) 198
(11286, 160, 1) 197
(11304, 160, 1) 196
(11322, 160, 1) 195
(11340, 160, 1) 194
(11358, 160, 1) 193
(11376, 160, 1) 192
(11394, 160, 1) 191
(11412, 160, 1) 190
(11430, 160, 1) 189
(11448, 160, 1) 188
(11466, 160, 1) 187
(11484, 160, 1) 186
(11502, 160, 1) 185
(11516, 160, 1) 184
(11534, 160, 1) 183
(11552, 160, 1) 182
(11570, 160, 1) 181
(11588, 160, 1) 180
(11606, 160, 1) 179
(11624, 160, 1) 178
(11642, 160, 1) 177
(11656, 160, 1) 176
(11674, 160, 1) 175
(11692, 160, 1) 174
(11710, 160, 1) 173
(11728, 160, 1) 172
(11746, 160, 1) 171
(11764, 160, 1) 170
(11782, 160, 1) 169
(11800, 160, 1) 168
(11818, 160, 1) 167
(11832, 160, 1) 166
(11850, 160, 1) 165
(11868, 160, 1) 164
(11882, 160, 1) 163
(11900, 160, 1) 162
(11918, 160, 1) 161
(11936, 160, 1) 160
(11954, 160, 1) 159
(11972, 160, 1) 158
(11990, 160, 1) 157
(12008, 160, 1) 156
(12022, 160, 1) 155
(12040, 160, 1) 154
(12058, 160, 1) 153
(12076, 160, 1) 152
(12094, 160, 1) 151
(12112, 160, 1) 150
(12130, 160, 1) 149
(12148, 160, 1) 148
(12166, 160, 1) 147
(12180, 160, 1) 146
(12194, 160, 1) 145
(12208, 160, 1) 144
(12226, 160, 1) 143
(12244, 160, 1) 142
(12262, 160, 1) 141
(12276, 160, 1) 140
(12294, 160, 1) 139
(12308, 160, 1) 138
(12326, 160, 1) 137
(12340, 160, 1) 136
(12358, 160, 1) 135
(12376, 160, 1) 134
(12394, 160, 1) 133
(12412, 160, 1) 132
(12426, 160, 1) 131
(12440, 160, 1) 130
(12458, 160, 1) 129
(12476, 160, 1) 128
(12494, 160, 1) 127
(12512, 160, 1) 126
(12530, 160, 1) 125
(12544, 160, 1) 124
(12558, 160, 1) 123
(12576, 160, 1) 122
(12594, 160, 1) 121
(12612, 160, 1) 120
(12626, 160, 1) 119
(12644, 160, 1) 118
(12662, 160, 1) 117
(12676, 160, 1) 116
(12694, 160, 1) 115
(12712, 160, 1) 114
(12730, 160, 1) 113
(12748, 160, 1) 112
(12762, 160, 1) 111
(12780, 160, 1) 110
(12798, 160, 1) 109
(12812, 160, 1) 108
(12826, 160, 1) 107
(12844, 160, 1) 106
(12862, 160, 1) 105
(12880, 160, 1) 104
(12898, 160, 1) 103
(12912, 160, 1) 102
(12926, 160, 1) 101
(12940, 160, 1) 100
(12958, 160, 1) 99
(12972, 160, 1) 98
(12990, 160, 1) 97
(13008, 160, 1) 96
(13022, 160, 1) 95
(13040, 160, 1) 94
(13054, 160, 1) 93
(13072, 160, 1) 92
(13090, 160, 1) 91
(13108, 160, 1) 90
(13126, 160, 1) 89
(13144, 160, 1) 88
(13162, 160, 1) 87
(13180, 160, 1) 86
(13194, 160, 1) 85
(13208, 160, 1) 84
(13226, 160, 1) 83
(13244, 160, 1) 82
(13262, 160, 1) 81
(13280, 160, 1) 80
(13294, 160, 1) 79
(13312, 160, 1) 78
(13330, 160, 1) 77
(13348, 160, 1) 76
(13366, 160, 1) 75
(13380, 160, 1) 74
(13394, 160, 1) 73
(13412, 160, 1) 72
(13430, 160, 1) 71
(13448, 160, 1) 70
(13466, 160, 1) 69
(13484, 160, 1) 68
(13502, 160, 1) 67
(13516, 160, 1) 66
(13534, 160, 1) 65
(13552, 160, 1) 64
(13570, 160, 1) 63
(13588, 160, 1) 62
(13602, 160, 1) 61
(13620, 160, 1) 60
(13638, 160, 1) 59
(13656, 160, 1) 58
(13670, 160, 1) 57
(13688, 160, 1) 56
(13706, 160, 1) 55
(13724, 160, 1) 54
(13738, 160, 1) 53
(13756, 160, 1) 52
(13774, 160, 1) 51
(13792, 160, 1) 50
(13810, 160, 1) 49
(13828, 160, 1) 48
(13846, 160, 1) 47
(13864, 160, 1) 46
(13882, 160, 1) 45
(13900, 160, 1) 44
(13918, 160, 1) 43
(13932, 160, 1) 42
(13950, 160, 1) 41
(13968, 160, 1) 40
(13982, 160, 1) 39
(13996, 160, 1) 38
(14014, 160, 1) 37
(14032, 160, 1) 36
(14050, 160, 1) 35
(14068, 160, 1) 34
(14082, 160, 1) 33
(14100, 160, 1) 32
(14118, 160, 1) 31
(14136, 160, 1) 30
(14150, 160, 1) 29
(14168, 160, 1) 28
(14186, 160, 1) 27
(14204, 160, 1) 26
(14218, 160, 1) 25
(14236, 160, 1) 24
(14254, 160, 1) 23
(14268, 160, 1) 22
(14286, 160, 1) 21
(14304, 160, 1) 20
(14322, 160, 1) 19
(14340, 160, 1) 18
(14358, 160, 1) 17
(14376, 160, 1) 16
(14394, 160, 1) 15
(14408, 160, 1) 14
(14426, 160, 1) 13
(14440, 160, 1) 12
(14458, 160, 1) 11
(14476, 160, 1) 10
(14494, 160, 1) 9
(14512, 160, 1) 8
(14526, 160, 1) 7
(14544, 160, 1) 6
(14562, 160, 1) 5
(14580, 160, 1) 4
(14598, 160, 1) 3
(14616, 160, 1) 2
(14634, 160, 1) 1
(14652, 160, 1) 0
(14670, 160, 1) 761

In [284]:
store_list[-1]

1115